# Silenciar todos os logs do Spark e Hadoop
rootLogger.level = ERROR
rootLogger.appenderRef.stdout.ref = console

appender.console.type = Console
appender.console.name = console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %msg%n

logger.spark.name = org.apache.spark
logger.spark.level = ERROR

logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = ERROR

logger.delta.name = io.delta
logger.delta.level = ERROR

logger.ivy.name = org.apache.ivy
logger.ivy.level = ERROR